name: Tests E2E

inputs:
  e2e_url:
    description: "Base url of deployment"
    required: true
  artifacts_sub_dir:
    description: "Sub directory for test artifacts"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Dependencies
      run: cd tests-e2e && npm ci

    - name: Install Playwright Browsers
      run: cd tests-e2e && npx playwright install --with-deps

    - name: Run E2E tests
      run: export E2E_URL=${{ inputs.e2e_url }} && cd tests-e2e && npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-e2e-report
        path: test-e2e-report/${{ inputs.artifacts_sub_dir }}/
        retention-days: 3
