name: Tests E2E
description: "E2E tests"
inputs:
  e2e_url:
    description: "Base url of deployment"
    required: true
  test_results_name:
    description: "Name of test results artifact uploaded to GitHub"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Dependencies
      run: cd tests-e2e && npm ci
      shell: bash

    - name: Get Playwright's Version
      id: playwright-version
      run: |
        cd tests-e2e
        PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Playwright Browsers for Playwright's Version
      id: cache-playwright-browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ steps.playwright_version.outputs.PLAYWRIGHT_VERSION }}

    - name: Setup Playwright
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
      shell: bash

    - name: Run E2E tests
      run: export E2E_URL=${{ inputs.e2e_url }} && cd tests-e2e && npx playwright test
      shell: bash

    - name: Store Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: ${{ inputs.test_results_name }}
        path: tests-e2e/playwright-report/
        retention-days: 3
