name: Tests E2E
description: "E2E tests"
inputs:
  e2e_url:
    description: "Base url of deployment"
    required: true
  shard_index:
    description: "Index of the shard to run"
    required: true
  shard_total:
    description: "Total number of shards"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: useblacksmith/setup-node@v5
      with:
        node-version: 23
        cache: "npm"

    - name: Install Dependencies
      run: cd tests-e2e && npm install
      shell: bash

    - name: Get Playwright's Version
      id: playwright-version
      run: |
        cd tests-e2e
        PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Playwright Browsers
      id: cache-playwright-browsers
      uses: useblacksmith/cache@v5
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}

    - name: Setup Playwright
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
      shell: bash

    - name: Run Playwright tests
      run: export E2E_URL=${{ inputs.e2e_url }} && cd tests-e2e && npm run test -- --shard ${{ inputs.shard_index }}/${{ inputs.shard_total }}
      shell: bash

    - name: Upload blob report to GitHub Actions Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      id: upload-playwright-report
      with:
        name: blob-report-${{ matrix.shardIndex }}
        path: tests-e2e/blob-report
        retention-days: 1
        overwrite: true
        include-hidden-files: true
        if-no-files-found: warn
