name: Tests E2E
description: "E2E tests"
inputs:
  e2e_url:
    description: "Base url of deployment"
    required: true
  test_results_name:
    description: "Name of test results artifact uploaded to GitHub"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Dependencies
      run: cd tests-e2e && npm ci
      shell: bash

    - name: Install Playwright Browsers
      run: cd tests-e2e && npx playwright install --with-deps
      shell: bash

    - name: Run E2E tests
      run: export E2E_URL=${{ inputs.e2e_url }} && cd tests-e2e && npx playwright test
      shell: bash

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: ${{ inputs.test_results_name }}
        path: tests-e2e/test-results/
        retention-days: 3
